name: flutter_music_player
description: flutter_music_player app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Comparing objects
  equatable: ^2.0.5

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Dependency injection
  get_it: ^7.6.0

  # Routing
  go_router: ^10.1.0

  # Finding common path on the filesystem
  path_provider: ^2.0.10

  # Local storage
  shared_preferences: ^2.2.0

  # Localization
  slang: &slang_version 3.23.0
  slang_flutter: *slang_version

  # Command-line tool for simplifies updating app's icons
  flutter_launcher_icons: ^0.13.1

  # Tool for simplifies updating app's splash screen
  flutter_native_splash: ^2.3.2

  # Lottie animation json file parser and viewer
  lottie: ^2.6.0

  # SVG file viewer
  flutter_svg: ^2.0.7

  # Show images from the internet and keep them in the cache directory
  cached_network_image: ^3.2.3

  # Provide the flutter scroll component drop-down refresh
  pull_to_refresh: ^2.0.0

  # Package for expand and collapse text
  readmore: ^2.2.0

  # Packages for working with Persian numbers and writings
  persian_number_utility: ^1.1.3
  persian_tools: ^1.0.3

  # Package for discover network connectivity status
  connectivity_plus: ^4.0.2

  # Animated page indicator
  smooth_page_indicator: ^1.1.0

  # Provides internationalization and localization facilities
  intl: ^0.18.0

  # Package for load yaml file
  yaml: ^3.1.2

  # Package for share content from app via the platform's native share dialog
  share_plus: ^7.2.0

  # Package contains pre-canned animations for commonly-desired effects.
  animations: ^2.0.8

  # Package for playing audio files
  assets_audio_player: ^3.1.1

  # Package for managing permissions
  permission_handler: ^11.1.0

  # Package for managing files and directories
  file_manager: ^1.0.2

  # Package for managing audio metadata
  flutter_media_metadata: ^1.0.0

dev_dependencies:
  slang_build_runner: *slang_version
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - pubspec.yaml

  fonts:
    - family: IranYekanXFaNum
      fonts:
        - asset: assets/fonts/IRANYekanXFaNum-Regular.ttf
        - asset: assets/fonts/IRANYekanXFaNum-Bold.ttf

    - family: IranYekanX
      fonts:
        - asset: assets/fonts/IRANYekanX-Regular.ttf
        - asset: assets/fonts/IRANYekanX-Bold.ttf
